service: sls-base

plugins:
    - serverless-webpack
 
custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

provider:
    name: aws
    runtime: nodejs14.x
    memorySize: 256
    region: eu-central-1
    stage: ${opt:stage, 'dev'}

functions:
    hello:
        handler: src/handlers/hello.handler
        events:
            - http:
                  method: GET
                  path: /hello
