service: sls-base

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 256
    region: eu-central-1
    stage: ${opt:stage, 'dev'}

functions:
    hello:
        handler: src/handlers/hello.handler
        events:
            - http:
                  method: GET
                  path: /hello
